- name: "Setup ShadowSocks"
  hosts: clouds
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Update APT
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true
      become_user: root

    - name: Install Outline setup script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh
        dest: /tmp/install_server.sh
        mode: '666'
        force: true
      become: true
      become_user: root

    - name: Setup Outline
      ansible.builtin.shell: /tmp/install_server.sh
      args:
        executable: /bin/bash
