- name: "Setup VLESS"
  hosts: clouds
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Update APT
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true
      become_user: root
